### ISSUE TITLE
Requirements decision: Multiple Content types support?

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_finders#1]
Directories allows site-builders to add any content type to a directory. This is done by adding a reference field to the parent directory channel. In doing so the following need to be done for the bundle:

 * Add the view mode for the bundle to the view rendered entity configuration for the list (not map) view;
 * Add the bundle to the index datasource;
 * Add the bundle, and view mode to index, to the rendered item of the search index;
 * Update block visibility to display the channel search block on the bundle item (really feel that might be optional).

----- 
## User stories 

**As a** content designer
**I want** to to create a new finder with multiple types of content
**So that** I can create a directory with pages and venues
**Notes**
Directories already have multiple content types. We think there will be other cases where multiple content types will be needed. Resources? 

**As a** content designer
**I want** to to create a new 'events' finder with a single event content type
**So that** I can create an events finder / listing with a simple event content type.
**Notes**

**Comment by ekes** [comment]
News is a single content type; 
Blogs is a single content type;
I'm assuming they would want to stay that way.

I'd guess consultations would be a single content type? @willguv 

Events,multiple content types, or single? @joachim-n

**Comment by joachim-n** [comment]
> Events,multiple content types, or single

Not sure! Possibly multiple content types to allow to easily use different recurring date widgets for purposes they're best suited to.

> This is done by adding a reference field to the parent directory channel. In doing so the following need to be done for the bundle

Might or might not be relevant, but I've been thinking for a while about using something other than the presence of a key field to define a node type as being a directory -- see https://github.com/localgovdrupal/localgov_events/issues/139.

**Comment by willguv** [comment]
> I'd guess consultations would be a single content type? [@willguv](https://github.com/willguv)

@ekes consultations may have a lot of variation so worth allowing for this

**Comment by willguv** [comment]
The code already supports multiple content types so this is covered
