### ISSUE TITLE
decide how to output the channel view

### ISSUE THREAD

**Issue by joachim-n** [localgovdrupal/localgov_finders#21]
In Directories, because the view ID is hardcoded, we output the rendered view with a pseudofield.

But in Finders, we're using a Views reference field to select the view.

This means we have access to the field formatter.

Does that do enough of what we want?

**Comment by joachim-n** [comment]
Hmm first problem is that viewsreference module doesn't allow configuring arguments at the field level -- only at the node level.

So we need a custom formatter anyway.

**Comment by willguv** [comment]
Fixed with a custom formatter
