### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by rupertj** [localgovdrupal/localgov_finders#28]
finders_events declares in its info file that it depends on date_recur_search_api, but date_recur_search_api isn't in the config.json for finders.

**Comment by joachim-n** [comment]
Do you mean the composer.json? That's normal -- finders_events will be moving out of that repo soon. It's just in there for convenience at the moment, so I don't have to keep jumping between repos when I make commits.

**Comment by rupertj** [comment]
Yeah, I did. I've got no idea where config.json came from. Anyway, I was thinking it'd make sense for finders_events to be in its own project, so I'll close this off.
