### ISSUE TITLE
Channel bundles -> Content type option doesn't appear

### ISSUE THREAD

**Issue by rupertj** [localgovdrupal/localgov_finders#29]
Create a new Finder entity.

Choose the channel bundle entity type.
Channel bundle content type does not appear.

If you choose the entry bundle entity type, then change the channel bundle entity type to something else, then back to Content, the Channel bundle content field does appear.

**Comment by joachim-n** [comment]
Are there any JS errors in the console? It was working for me, though either I happened to do it in the right order, or I've forgotten to commit a file!

**Comment by rupertj** [comment]
Yes there are!

ResponseText: The website encountered an unexpected error. Try again later.Drupal\Component\Plugin\Exception\PluginNotFoundException: The &quot;container&quot; entity type does not exist. in Drupal\Core\Entity\EntityTypeManager-&gt;getDefinition() (line 142 of core/lib/Drupal/Core/Entity/EntityTypeManager.php). Drupal\finders\Element\EntityBundles::processEntityBundles()
call_user_func_array() (Line: 1006)

**Comment by joachim-n** [comment]
> The "container" entity type does not exist

That sounds like the top-level form element in the custom form element plugin is somehow getting picked up as the value for the entity type.

**Comment by joachim-n** [comment]
Can you debug around line 100 of EntityBundles? $selected_entity_type_id is getting set to the wrong thing -- almost certainly because I frankencoded this class from Action Link module....

**Comment by rupertj** [comment]
$selected_entity_type_id is getting set to 'container' on line 100, which is the case where it's not including 'container' in the element parents.

The chosen entity_type_is is in the formState's values at: $form_state->values["entries"]["container"]["entity_type_id"];

**Comment by joachim-n** [comment]
Thanks! 

I know what's gone wrong -- in Action Link I added the method that gets the value for a form element, in an attempt to remove the 'container' nesting from the values -- which doesn't quite work. Without that, there's never a case when it's not nested like that. You can remove that clause completely.

**Comment by rupertj** [comment]
Ta. I had to do a bit more than that to handle some confusion between the empty string and null to make it work. It's in PR #31 into your branch.

**Comment by joachim-n** [comment]
Thanks!
