### ISSUE TITLE
Exception when creating a new Finder.

### ISSUE THREAD

**Issue by rupertj** [localgovdrupal/localgov_finders#30]
The website encountered an unexpected error. Try again later.

Drupal\search_api\SearchApiException: The "date_recur:node__finders_events_date" plugin does not exist. Valid plugin IDs for Drupal\search_api\Datasource\DatasourcePluginManager are: date_recur:node__localgov_event_date, entity:block_content, entity:content_moderation_state, entity:crop, entity:file, entity:geo_entity, entity:ofsted_registration, entity:localgov_alert_banner, entity:localgov_directories_facets, entity:localgov_geo, entity:review_date, entity:media, entity:menu_link_content, entity:node, entity:paragraphs_library_item, entity:path_alias, entity:preview_link, entity:radioactivity, entity:redirect, entity:scheduled_transition, entity:search_api_task, entity:taxonomy_term, entity:user, entity:webform_submission, entity:paragraph in Drupal\search_api\Utility\PluginHelper->createIndexPlugin() (line 81 of modules/contrib/search_api/src/Utility/PluginHelper.php).
Drupal\Core\Plugin\DefaultPluginManager->getDefinition() (Line: 16)
Drupal\Core\Plugin\Factory\ContainerFactory->createInstance() (Line: 83)
Drupal\Component\Plugin\PluginManagerBase->createInstance() (Line: 78)
Drupal\search_api\Utility\PluginHelper->createIndexPlugin() (Line: 130)
Drupal\search_api\Utility\PluginHelper->createDatasourcePlugin() (Line: 459)
Drupal\finders\Plugin\FinderType\FinderTypeBase->getIndexDatasource() (Line: 172)
Drupal\finders\Plugin\FinderType\FinderTypeBase->alterSearchIndex() (Line: 242)
Drupal\finders\FinderConfigManager->ensureFinderConfig() (Line: 234)
Drupal\finders\Entity\Finder->postSave() (Line: 563)
Drupal\Core\Entity\EntityStorageBase->doPostSave() (Line: 489)
Drupal\Core\Entity\EntityStorageBase->save() (Line: 257)
Drupal\Core\Config\Entity\ConfigEntityStorage->save() (Line: 354)
Drupal\Core\Entity\EntityBase->save() (Line: 614)
Drupal\Core\Config\Entity\ConfigEntityBase->save() (Line: 293)
Drupal\Core\Entity\EntityForm->save() (Line: 162)
Drupal\finders\Form\FinderForm->save()
call_user_func_array() (Line: 129)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers() (Line: 67)
Drupal\Core\Form\FormSubmitter->doSubmitForm() (Line: 597)
Drupal\Core\Form\FormBuilder->processForm() (Line: 326)
Drupal\Core\Form\FormBuilder->buildForm() (Line: 73)
Drupal\Core\Controller\FormController->getContentResult()
call_user_func_array() (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 638)
Drupal\Core\Render\Renderer->executeInRenderContext() (Line: 121)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext() (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 181)
Symfony\Component\HttpKernel\HttpKernel->handleRaw() (Line: 76)
Symfony\Component\HttpKernel\HttpKernel->handle() (Line: 53)
Drupal\Core\StackMiddleware\Session->handle() (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle() (Line: 28)
Drupal\Core\StackMiddleware\ContentLength->handle() (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass() (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle() (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle() (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle() (Line: 36)
Drupal\Core\StackMiddleware\AjaxPageState->handle() (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle() (Line: 741)
Drupal\Core\DrupalKernel->handle() (Line: 23)

I'd just submitted the form to create a new Finder entity. Events type, pointing to an Events Channel content type I just made and the existing events type.

**Comment by joachim-n** [comment]
Have you got date_recur and the search API / date_recur glue module installed? They might be missing as dependencies.

I was concerned about the order of plugin derivation and bundle field declaration, but the tests for this pass!

**Comment by joachim-n** [comment]
Did this turn out to be a missing dependency?

**Comment by joachim-n** [comment]
Just tried this on a fresh install and it works.
