### ISSUE TITLE
config-level validation for finders

### ISSUE THREAD

**Issue by joachim-n** [localgovdrupal/localgov_finders#32]
Validation should happen at the config schema level:

- an entry bundle can only be in one finder as an entry*
- a channel bundle can only be in one finder as a channel*
- only one entity type for entries
- only one entity type for channels

- [*] it would probably be ok to have an entry in one finder be a channel in another

**Comment by andybroomfield** [comment]
> an entry bundle can only be in one finder as an entry*

I wouldn't nessacarly assume this. There is at least one potential case coming up where we might want to have our directory providers, where they are council services, be exposed to another 'finder' like channel that shows a different display mode of the same entry. We could mitigate this by wrapping it in another node or entity, but it would be handy not to have to duplicate the facets we add to them. Would that complicate things?

**Comment by joachim-n** [comment]
You can have your entry nodes in multiple channels, but *of the same finder*.

A different finder will want to add its own fields, index, and view, etc. You could sidestep all that with a custom finder type plugin though.

**Comment by joachim-n** [comment]
Done.
